name: CI

on:
  # push:
  #   branches: [main, master, develop, "**"]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check-types

      - name: Lint code
        run: npm run lint -- --max-warnings=0

      - name: Run tests
        run: xvfb-run -a npm run test -- --ci

      - name: Check code coverage
        run: npm run check-coverage

      - name: Build extension
        run: npm run package

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: extension-build
          path: dist/
          retention-days: 7
